<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Films [
    <!ELEMENT Films (Film+)>
    <!ELEMENT Film (title, posterFileName, releaseDate, budget?, gross?, genre+, actor*, director+, writer+, description, runtime)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT posterFileName (#PCDATA)>
    <!ELEMENT releaseDate (#PCDATA)>
    <!ELEMENT budget (#PCDATA)>
    <!ELEMENT gross (#PCDATA)>
    <!ELEMENT genre (#PCDATA)>
    <!ELEMENT actor (#PCDATA)>
    <!ELEMENT director (#PCDATA)>
    <!ELEMENT writer (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT runtime (#PCDATA)>
    ]>

<Films>

    <Film>
        <title>Fantastic Beasts and Where to Find Them</title>
        <posterFileName>f1.png</posterFileName>
        <releaseDate>18.11.2016</releaseDate>
        <budget>180000000</budget>
        <gross>814044001</gross>
        <genre>Adventure</genre>
        <genre>Family</genre>
        <genre>Fantasy</genre>
        <actor>Eddie Redmayne</actor>
        <actor>Alison Sudol</actor>
        <actor>Dan Fogler</actor>
        <actor>Katherine Waterston</actor>
        <director>David Yates</director>
        <writer>J.K. Rowling</writer>
        <description>In mid-1920s New York, Newt Scamander, a British young activist wizard, arrives in the city, holding a mysterious leather suitcase that shelters diverse and magical creatures that exist among us. Amid an already fragile equilibrium of secrecy, and the increasing disasters ascribed to the dark wizard, Gellert Grindelwald, Newt's precious suitcase goes missing, and to make matters worse, several creatures manage to escape. Before long, this unforeseen complication catches Senior Auror Percival Graves' attention who targets Newt, against the backdrop of an invisible, devastating, and utterly unpredictable menace that still wreaks havoc on 5th Avenue. In the end, is there a hidden agenda behind Graves' intentions? Moreover, what will happen to the remaining fantastic beasts that are still on the loose?</description>
        <runtime>132</runtime>
    </Film>

    <Film>
        <title>The Theory of Everything</title>
        <posterFileName>f2.jpg</posterFileName>
        <releaseDate>26.11.2014</releaseDate>
        <budget>15000000</budget>
        <gross>123726688</gross>
        <genre>Biography</genre>
        <genre>Drama</genre>
        <genre>Romance</genre>
        <actor>Eddie Redmayne</actor>
        <actor>Felicity Jones</actor>
        <actor>Tom Prior</actor>
        <director>James Marsh</director>
        <writer>Anthony McCarten</writer>
        <writer>Jane Hawking</writer>
        <description>The Theory of Everything is the story of the most brilliant and celebrated physicist of our time, Stephen Hawking, and Jane Wilde, the arts student he fell in love with while studying at Cambridge in the 1960s. Little was expected from Hawking, a bright but shiftless student of cosmology, after he was given just two years to live following the diagnosis of a fatal illness (ALS) at 21 years of age. He became galvanized, however, by the love Jane Wilde, and went on to be called the "successor to Einstein," as well as a husband and father to their three children. Over the course of their marriage, however, as Stephen's body collapsed and his academic renown soared, fault lines were exposed that tested the resolve of their relationship and dramatically altered the course of both of their lives.</description>
        <runtime>123</runtime>
    </Film>

    <Film>
        <title>Fantastic Beasts: The Crimes of Grindelwald</title>
        <posterFileName>f3.jpg</posterFileName>
        <releaseDate>16.11.2018</releaseDate>
        <budget>200000000</budget>
        <gross>654855901</gross>
        <genre>Adventure</genre>
        <genre>Family</genre>
        <genre>Fantasy</genre>
        <actor>Eddie Redmayne</actor>
        <actor>Alison Sudol</actor>
        <actor>Dan Fogler</actor>
        <actor>Katherine Waterston</actor>
        <actor>Johnny Depp</actor>
        <director>David Yates</director>
        <writer>J.K. Rowling</writer>
        <description>In an effort to thwart Grindelwald's plans of raising pure-blood wizards to rule over all non-magical beings, Albus Dumbledore enlists his former student Newt Scamander, who agrees to help, though he's unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.</description>
        <runtime>134</runtime>
    </Film>

    <Film>
        <title>Pirates of the Caribbean: The Curse of the Black Pearl</title>
        <posterFileName>f4.jpg</posterFileName>
        <releaseDate>09.07.2003</releaseDate>
        <budget>140000000</budget>
        <gross>654264015</gross>
        <genre>Action</genre>
        <genre>Adventure</genre>
        <genre>Fantasy</genre>
        <actor>Johnny Depp</actor>
        <actor>Geoffrey Rush</actor>
        <actor>Keira Knightley</actor>
        <actor>Orlando Bloom</actor>
        <director>Gore Verbinski</director>
        <writer>Ted Elliott</writer>
        <writer>Terry Rossio</writer>
        <writer>Stuart Beattie</writer>
        <description>This swash-buckling tale follows the quest of Captain Jack Sparrow, a savvy pirate, and Will Turner, a resourceful blacksmith, as they search for Elizabeth Swann. Elizabeth, the daughter of the governor and the love of Will's life, has been kidnapped by the feared Captain Barbossa. Little do they know, but the fierce and clever Barbossa has been cursed. He, along with his large crew, are under an ancient curse, doomed for eternity to neither live, nor die. That is, unless a blood sacrifice is made.</description>
        <runtime>143</runtime>
    </Film>

    <Film>
        <title>Pirates of the Caribbean: Dead Man's Chest</title>
        <posterFileName>f5.jpg</posterFileName>
        <releaseDate>07.07.2006</releaseDate>
        <budget>225000000</budget>
        <gross>1066179747</gross>
        <genre>Action</genre>
        <genre>Adventure</genre>
        <genre>Fantasy</genre>
        <actor>Johnny Depp</actor>
        <actor>Geoffrey Rush</actor>
        <actor>Keira Knightley</actor>
        <actor>Orlando Bloom</actor>
        <actor>Bill Nighy</actor>
        <director>Gore Verbinski</director>
        <writer>Ted Elliott</writer>
        <writer>Terry Rossio</writer>
        <writer>Stuart Beattie</writer>
        <description>Once again we're plunged into the world of sword fights and "savvy" pirates. Captain Jack Sparrow is reminded he owes a debt to Davy Jones, who captains the flying Dutchman, a ghostly ship, with a crew from hell. Facing the "locker" Jack must find the heart of Davy Jones but to save himself he must get the help of quick-witted Will Turner and Elizabeth Swan. If that's not complicated enough, Will and Elizabeth are sentenced to hang, unless Will can get Lord Cutler Beckett Jack's compass. Will is forced to join another crazy adventure with Jack.</description>
        <runtime>151</runtime>
    </Film>

    <Film>
        <title>Pirates of the Caribbean: At World's End</title>
        <posterFileName>f6.jpg</posterFileName>
        <releaseDate>25.05.2007</releaseDate>
        <budget>300000000</budget>
        <gross>960996492</gross>
        <genre>Action</genre>
        <genre>Adventure</genre>
        <genre>Fantasy</genre>
        <actor>Johnny Depp</actor>
        <actor>Geoffrey Rush</actor>
        <actor>Keira Knightley</actor>
        <actor>Orlando Bloom</actor>
        <director>Gore Verbinski</director>
        <writer>Ted Elliott</writer>
        <writer>Terry Rossio</writer>
        <writer>Stuart Beattie</writer>
        <description>After Elizabeth, Will, and Captain Barbossa rescue Captain Jack Sparrow from the land of the dead, they must face their foes, Davy Jones and Lord Cutler Beckett. Beckett, now with control of Jones' heart, forms a dark alliance with him in order to rule the seas and wipe out the last of the Pirates. Now, Jack, Barbossa, Will, Elizabeth, Tia Dalma, and crew must call the Pirate Lords from the four corners of the globe, including the infamous Sao Feng, to gathering. The Pirate Lords want to release the goddess Calypso, Davy Jones's damned lover, from the trap they sent her to out of fear, in which the Pirate Lords must combine the 9 pieces that bound her by ritual to undo it and release her in hopes that she will help them fight. With this, all pirates will stand together and will make their final stand for freedom against Beckett, Jones, Norrington, the Flying Dutchman, and the entire East India Trading Company. </description>
        <runtime>169</runtime>
    </Film>

    <Film>
        <title>Pirates of the Caribbean: Dead Men Tell No Tales</title>
        <posterFileName>f7.jpg</posterFileName>
        <releaseDate>26.05.2017</releaseDate>
        <budget>230000000</budget>
        <gross>794881442</gross>
        <genre>Action</genre>
        <genre>Adventure</genre>
        <genre>Fantasy</genre>
        <actor>Johnny Depp</actor>
        <actor>Geoffrey Rush</actor>
        <actor>Keira Knightley</actor>
        <actor>Orlando Bloom</actor>
        <director>Joachim RÃ¸nning</director>
        <director>Espen Sandberg</director>
        <writer>Jeff Nathanson</writer>
        <writer>Ted Elliott</writer>
        <writer>Terry Rossio</writer>
        <description>Captain Jack Sparrow (Johnny Depp) finds the winds of ill-fortune blowing even more strongly when deadly ghost pirates led by his old nemesis, the terrifying Captain Salazar (Javier Bardem), escape from the Devil's Triangle, determined to kill every pirate at sea...including him. Captain Jack's only hope of survival lies in seeking out the legendary Trident of Poseidon, a powerful artifact that bestows upon its possessor total control over the seas.</description>
        <runtime>129</runtime>
    </Film>

    <Film>
        <title>The Lord of the Rings: The Fellowship of the Ring</title>
        <posterFileName>f8.jpg</posterFileName>
        <releaseDate>19.12.2001</releaseDate>
        <budget>93000000</budget>
        <gross>897690072</gross>
        <genre>Action</genre>
        <genre>Adventure</genre>
        <genre>Drama</genre>
        <genre>Fantasy</genre>
        <actor>Elijah Wood</actor>
        <actor>Viggo Mortensen</actor>
        <actor>Ian McKellen</actor>
        <actor>Orlando Bloom</actor>
        <actor>Alan Howard</actor>
        <director>Peter Jackson</director>
        <writer>J.R.R. Tolkien</writer>
        <writer>Fran Walsh</writer>
        <writer>Philippa Boyens</writer>
        <description>An ancient Ring thought lost for centuries has been found, and through a strange twist of fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to the Cracks of Doom in order to destroy it. However, he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Boromir, and his three Hobbit friends Merry, Pippin, and Samwise. Through mountains, snow, darkness, forests, rivers and plains, facing evil and danger at every corner the Fellowship of the Ring must go. Their quest to destroy the One Ring is the only hope for the end of the Dark Lords reign.</description>
        <runtime>172</runtime>
    </Film>

    <Film>
        <title>The Lord of the Rings: The Two Towers</title>
        <posterFileName>f9.jpg</posterFileName>
        <releaseDate>18.12.2002</releaseDate>
        <budget>94000000</budget>
        <gross>947495095</gross>
        <genre>Action</genre>
        <genre>Adventure</genre>
        <genre>Drama</genre>
        <genre>Fantasy</genre>
        <actor>Elijah Wood</actor>
        <actor>Viggo Mortensen</actor>
        <actor>Ian McKellen</actor>
        <actor>Orlando Bloom</actor>
        <director>Peter Jackson</director>
        <writer>J.R.R. Tolkien</writer>
        <writer>Fran Walsh</writer>
        <writer>Philippa Boyens</writer>
        <description>The continuing quest of Frodo and the Fellowship to destroy the One Ring. Frodo and Sam discover they are being followed by the mysterious Gollum. Aragorn, the Elf archer Legolas, and Gimli the Dwarf encounter the besieged Rohan kingdom, whose once great King Theoden has fallen under Saruman's deadly spell.</description>
        <runtime>179</runtime>
    </Film>

    <Film>
        <title>The Lord of the Rings: The Return of the King</title>
        <posterFileName>f10.jpg</posterFileName>
        <releaseDate>17.12.2003</releaseDate>
        <budget>94000000</budget>
        <gross>1146030912</gross>
        <genre>Action</genre>
        <genre>Adventure</genre>
        <genre>Drama</genre>
        <genre>Fantasy</genre>
        <actor>Elijah Wood</actor>
        <actor>Viggo Mortensen</actor>
        <actor>Ian McKellen</actor>
        <actor>Orlando Bloom</actor>
        <actor>Alan Howard</actor>
        <director>Peter Jackson</director>
        <writer>J.R.R. Tolkien</writer>
        <writer>Fran Walsh</writer>
        <writer>Philippa Boyens</writer>
        <description>The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Frodo and Sam reach Mordor in their quest to destroy the One Ring, while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith. </description>
        <runtime>201</runtime>
    </Film>

<!--
    <Film>
        <title></title>
        <posterFileName></posterFileName>
        <releaseDate></releaseDate>
        <budget></budget>
        <gross></gross>
        <genre></genre>
        <actor></actor>
        <director></director>
        <writer></writer>
        <description></description>
        <runtime></runtime>
    </Film>
-->

</Films>